/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from 'mongoose';

/**
 * Lean version of OrganizationDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `OrganizationDocument.toObject()`. To avoid conflicts with model names, use the type alias `OrganizationObject`.
 * ```
 * const organizationObject = organization.toObject();
 * ```
 */
export type Organization = {
  name: string;
  description: string;
  access_level?: 'public' | 'private';
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of OrganizationDocument (type alias of `Organization`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Organization } from "../models"
 * import { OrganizationObject } from "../interfaces/mongoose.gen.ts"
 *
 * const organizationObject: OrganizationObject = organization.toObject();
 * ```
 */
export type OrganizationObject = Organization;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type OrganizationQuery = mongoose.Query<any, OrganizationDocument, OrganizationQueries> & OrganizationQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `OrganizationSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type OrganizationQueries = {};

export type OrganizationMethods = {};

export type OrganizationStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Organization = mongoose.model<OrganizationDocument, OrganizationModel>("Organization", OrganizationSchema);
 * ```
 */
export type OrganizationModel = mongoose.Model<OrganizationDocument, OrganizationQueries> & OrganizationStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Organization schema instances:
 * ```
 * const OrganizationSchema: OrganizationSchema = new mongoose.Schema({ ... })
 * ```
 */
export type OrganizationSchema = mongoose.Schema<
  OrganizationDocument,
  OrganizationModel,
  OrganizationMethods,
  OrganizationQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Organization = mongoose.model<OrganizationDocument, OrganizationModel>("Organization", OrganizationSchema);
 * ```
 */
export type OrganizationDocument = mongoose.Document<mongoose.Types.ObjectId, OrganizationQueries> &
  OrganizationMethods & {
    name: string;
    description: string;
    access_level?: 'public' | 'private';
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of OrganizationMemberDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `OrganizationMemberDocument.toObject()`. To avoid conflicts with model names, use the type alias `OrganizationMemberObject`.
 * ```
 * const organizationmemberObject = organizationmember.toObject();
 * ```
 */
export type OrganizationMember = {
  organizationId: Organization['_id'] | Organization;
  userId: User['_id'] | User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of OrganizationMemberDocument (type alias of `OrganizationMember`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { OrganizationMember } from "../models"
 * import { OrganizationMemberObject } from "../interfaces/mongoose.gen.ts"
 *
 * const organizationmemberObject: OrganizationMemberObject = organizationmember.toObject();
 * ```
 */
export type OrganizationMemberObject = OrganizationMember;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type OrganizationMemberQuery = mongoose.Query<any, OrganizationMemberDocument, OrganizationMemberQueries> &
  OrganizationMemberQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `OrganizationMemberSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type OrganizationMemberQueries = {};

export type OrganizationMemberMethods = {};

export type OrganizationMemberStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const OrganizationMember = mongoose.model<OrganizationMemberDocument, OrganizationMemberModel>("OrganizationMember", OrganizationMemberSchema);
 * ```
 */
export type OrganizationMemberModel = mongoose.Model<OrganizationMemberDocument, OrganizationMemberQueries> &
  OrganizationMemberStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new OrganizationMember schema instances:
 * ```
 * const OrganizationMemberSchema: OrganizationMemberSchema = new mongoose.Schema({ ... })
 * ```
 */
export type OrganizationMemberSchema = mongoose.Schema<
  OrganizationMemberDocument,
  OrganizationMemberModel,
  OrganizationMemberMethods,
  OrganizationMemberQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const OrganizationMember = mongoose.model<OrganizationMemberDocument, OrganizationMemberModel>("OrganizationMember", OrganizationMemberSchema);
 * ```
 */
export type OrganizationMemberDocument = mongoose.Document<mongoose.Types.ObjectId, OrganizationMemberQueries> &
  OrganizationMemberMethods & {
    organizationId: OrganizationDocument['_id'] | OrganizationDocument;
    userId: UserDocument['_id'] | UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  name?: string;
  email: string;
  password?: string;
  isTemporary?: boolean;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of UserDocument (type alias of `User`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { User } from "../models"
 * import { UserObject } from "../interfaces/mongoose.gen.ts"
 *
 * const userObject: UserObject = user.toObject();
 * ```
 */
export type UserObject = User;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type UserQuery = mongoose.Query<any, UserDocument, UserQueries> & UserQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `UserSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type UserQueries = {};

export type UserMethods = {};

export type UserStatics = {
  createTemporaryUser: (this: UserModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserModel = mongoose.Model<UserDocument, UserQueries> & UserStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new User schema instances:
 * ```
 * const UserSchema: UserSchema = new mongoose.Schema({ ... })
 * ```
 */
export type UserSchema = mongoose.Schema<UserDocument, UserModel, UserMethods, UserQueries>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserDocument = mongoose.Document<mongoose.Types.ObjectId, UserQueries> &
  UserMethods & {
    name?: string;
    email: string;
    password?: string;
    isTemporary?: boolean;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<infer U>
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module 'mongoose' {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any,
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>,
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
